name: Build
on: [push]
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        type: [Debug, Release]
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: VC Vars
        # Setup vcvars on Windows
        # MSVC's address sanitizer attaches dependencies to several DLLs which are not in PATH
        # vcvars will add them to PATH and allow msvc asan executables to run
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.type }}
      - name: Build
        run: cmake --build . --config ${{ matrix.type }}
        env:          
          UBSAN_OPTIONS: halt_on_error=1
