name: Build
on: [push]
jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        type: [Debug, Release]
        compiler: [gcc, clang-10, clang-12]
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
      - name: Install Dependencies
        run: |
          sudo apt-get install -y libglew-dev
          sudo apt-get install libgtk-3-dev
          sudo apt-get install libudev-dev
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.type }}
      - name: Build
        run: cmake --build . --config ${{ matrix.type }}
        env:          
          UBSAN_OPTIONS: halt_on_error=1
  build-windows:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        type: [Debug, Release]
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
      - name: VC Vars
        # Setup vcvars on Windows
        # MSVC's address sanitizer attaches dependencies to several DLLs which are not in PATH
        # vcvars will add them to PATH and allow msvc asan executables to run
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Configure
        run: cmake . -DCMAKE_BUILD_TYPE=${{ matrix.type }}
      - name: Build
        run: cmake --build . --config ${{ matrix.type }}
        env:          
          UBSAN_OPTIONS: halt_on_error=1
